{% set name = "django-vite" %}
{% set version = "3.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/django-vite-{{ version }}.tar.gz
  sha256: 043ab5068b4c66eb33cb26c5215a6dfe275d3c4de15d59b0b7b97b4567912fb0

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - django >=3.2

test:
  imports:
    - django_vite
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/MrBin99/django-vite
  summary: Integration of Vite in a Django project.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
